apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: web-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello Ragav</title>
    </head>
    <body>
        <h1>Hello Ragav Welcome to nginx!</h1>
        <p>If you see this page, the nginx web server is successfully installed and working. Further configuration is required.</p>
        <p>For online documentation and support please refer to nginx.org.</p>
        <p>Commercial support is available at nginx.com.</p>
        <p>Thank you for using nginx.</p>
    </body>
    </html>

