apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: app-demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx-demo:v1       # Your Docker image
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html          # Must match your ConfigMap name

