apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: app-demo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: localhost:5000/nginx-demo:v1
        ports:
        - containerPort: 80

