apiVersion: v1
kind: Namespace
metadata:
  name: app-demo-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-pod
  namespace: app-demo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: app-demo-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-demo-html
  namespace: app-demo-ns
data:
  index.html: |
    <html>
      <body>
        <h1 style="color:green;">Hello Ragav!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: app-demo-ns
spec:
  selector:
    app: app-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30909
  type: NodePort

