apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: app-demo-ns
spec:
  selector:
    app: nginx-demo       # must match your Deployment label
  ports:
    - protocol: TCP
      port: 80             # service port inside cluster
      targetPort: 80       # container port (nginx listens on 80)
      nodePort: 30081      # host port for external access
  type: NodePort           # exposes it outside the cluster
