apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: app-demo-ns
spec:
  type: NodePort
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80         # service port inside cluster
      targetPort: 80   # container port (nginx listens on 80)
      nodePort: 30081  # valid NodePort

